# Generated by Django 5.2 on 2025-07-03 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_session_expire_alter_profile_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 13, 58, 50, 159227, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
