# Generated by Django 5.2 on 2025-07-04 13:33

import datetime
import django.db.models.deletion
import user.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_session_expire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 13, 33, 23, 787934, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор токена')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=user.models.get_token_expire_time, verbose_name='Срок жизни токена')),
                ('revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh',
                'indexes': [models.Index(fields=['jti'], name='refresh_jti_fe4f90_idx'), models.Index(fields=['revoked'], name='refresh_revoked_cbca45_idx')],
            },
        ),
    ]
