# Generated by Django 5.2 on 2025-07-10 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_session_expire_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 9, 12, 27, 39, 169947, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
