# Generated by Django 5.2 on 2025-07-13 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_session_expire_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 14, 12, 58, 456449, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
