# Generated by Django 5.2 on 2025-07-21 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 20, 52, 18, 461279, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
