# Generated by Django 5.2 on 2025-07-22 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 21, 19, 15, 30, 45354, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
