# Generated by Django 5.2 on 2025-08-04 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 8, 52, 31, 359573, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
