# Generated by Django 5.2 on 2025-08-13 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 7, 45, 54, 784450, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
