# Generated by Django 5.2 on 2025-08-13 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 11, 28, 59, 84756, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
