# Generated by Django 5.2 on 2025-08-16 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 13, 47, 43, 128231, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
