# Generated by Django 5.2 on 2025-08-26 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 11, 52, 4, 414849, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
