# Generated by Django 5.2 on 2025-08-26 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_profile_is_online_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 25, 12, 22, 36, 31477, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
