# Generated by Django 5.2 on 2025-08-28 09:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_profile_session_expire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 27, 9, 55, 43, 219325, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_number', models.IntegerField(null=True)),
                ('main', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to=settings.AUTH_USER_MODEL)),
                ('secondary', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Crew',
                'indexes': [models.Index(fields=['crew_number'], name='Crew_crew_nu_5e16e9_idx')],
            },
        ),
    ]
