# Generated by Django 5.2 on 2025-08-28 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_profile_session_expire_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_number',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('doctor', 'Врач'), ('dispatcher', 'Диспетчер'), ('paramedic', 'Фельдшер')], default='doctor', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 27, 10, 10, 43, 109721, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
