# Generated by Django 5.2 on 2025-09-26 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_crew_crew_number_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 10, 9, 14, 594790, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
