# Generated by Django 5.2 on 2025-09-26 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 11, 55, 30, 651357, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
    ]
