# Generated by Django 5.2 on 2025-12-19 11:47

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='crew_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=user.models.get_expire_time, verbose_name='Срок действия сессии'),
        ),
    ]
