# Generated by Django 5.2 on 2025-07-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='csrf_token',
        ),
    ]
