export const defaultValue = {
  common_data: {
    general_assessment: "satisfactory",
    сonsciousness: "clear",
    glasgow_scale: 15,
    body_position: "active",
    normal_blood_pressure_systolic: 120,
    normal_blood_pressure_diastolic: 80,
  },
  parameters: {
    temperature: 36.6,
    respiratory_rate: 16,
    heartbite: 60,
    saturation: 98,
    pulse: 60,
    blood_pressure_systolic: 120,
    blood_pressure_diastolic: 80,
    blood_glucose: 5.5,
  },
  skin_data: {
    dry_skin: "dry",
    color_skin: "normal",
    jaundice: "Нет",
    rash: "none",
    throat: "calm",
    tonsils: "Не увеличены",
    lymph_nodes: "Не увеличены",
    swelling: "none",
  },
  air_data: {
    respiratory_type: "vesicular",
    wheezing: "none",
    wheezing_localisation: "Нет",
    dyspnea: "none",
  },
  heart_data: {
    heart_rate_deficit: false,
    heart_tone_accent: "Нет",
    rhythmic_tone: "rhythmic",
    tone_of_heart: "clear",
    murmur: "none",
    rhythmic_pulse: "rhythmic",
    characteristic_pulse: "normal",
  },
  stomach_data: {
    liver: "Не увеличена",
    pain_stomach: "Нет",
    characteristic_stomach: "painless",
    involved_in_the_act_of_breathing: true,
    formed_type_stool: "formed",
    regular_stool: "regular",
    rate_stool: 1,
    is_shchetkin_blumberg: false,
    is_voskresensky: false,
    is_ortner: false,
    is_rovzinga: false,
    is_pasternatsky: false,
    is_sitkovsky: false,
    is_obraztsova: false,
    is_murphy: false,
  },
  nervous_data: {
    behaviour: "calm",
    reaction_to_light: "yes",
    pupils_of_the_eyes: "normal",
    anisocoria: false,
    nystagmus: false,
    focal_signs: false,
    speech: "clear",
    none_symptoms: false,
    nuchal_rigidity: false,
    is_kernig_symptom: false,
    is_brudzinski_symptom: false,
    paralysis: "none",
    sensitive: "preserved",
  },    
  urinary_data: {
    kidney_punch: "negative_both",
    characteristic_urine: "light_yellow",
    with_inclusions: false,
    with_sediment: false,
    painless_urination: "painless",
    characteristic_urination: "free",
  },
  aid_data: {
    aid_effect: "improvement",
  },
};
