# Generated by Django 5.2 on 2025-04-21 08:52

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=256, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('doctor', 'Врач'), ('dispatcher', 'Диспетчер')], default='doctor', max_length=20, verbose_name='Роль')),
                ('uuid_session', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор сессии')),
                ('session_expire', models.DateTimeField(default=datetime.datetime(2025, 4, 21, 8, 52, 49, 395656, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['uuid_session'], name='profiles_uuid_se_ef1378_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['session_expire'], name='profiles_session_8071e3_idx'),
        ),
    ]
