# Generated by Django 5.2 on 2025-04-21 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_delete_customuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Срок действия сессии'),
        ),
    ]
