# Generated by Django 5.2 on 2025-04-21 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_profile_session_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="session_expire",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Срок действия сессии"),
        ),
    ]
