# Generated by Django 5.2 on 2025-07-03 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_session_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 13, 56, 27, 594452, tzinfo=datetime.timezone.utc), verbose_name='Срок действия сессии'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='Отчество'),
        ),
    ]
