# Generated by Django 5.2 on 2025-07-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_card_csrf_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='submit',
        ),
    ]
