# Generated by Django 5.2 on 2025-07-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_card',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
