# Generated by Django 5.2 on 2025-07-13 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_card_date_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.RemoveField(
            model_name='card',
            name='address',
        ),
        migrations.RemoveField(
            model_name='card',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='card',
            name='anamnesis',
        ),
        migrations.RemoveField(
            model_name='card',
            name='anisocoria',
        ),
        migrations.RemoveField(
            model_name='card',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='card',
            name='behaviour',
        ),
        migrations.RemoveField(
            model_name='card',
            name='blood_glucose_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='blood_glucose_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='blood_pressure_diastolic_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='blood_pressure_diastolic_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='blood_pressure_systolic_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='blood_pressure_systolic_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='body_position',
        ),
        migrations.RemoveField(
            model_name='card',
            name='call_end_time',
        ),
        migrations.RemoveField(
            model_name='card',
            name='characteristic_pulse',
        ),
        migrations.RemoveField(
            model_name='card',
            name='characteristic_stomach',
        ),
        migrations.RemoveField(
            model_name='card',
            name='characteristic_urination',
        ),
        migrations.RemoveField(
            model_name='card',
            name='characteristic_urine',
        ),
        migrations.RemoveField(
            model_name='card',
            name='color_skin',
        ),
        migrations.RemoveField(
            model_name='card',
            name='date_card',
        ),
        migrations.RemoveField(
            model_name='card',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='card',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='card',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='card',
            name='dry_skin',
        ),
        migrations.RemoveField(
            model_name='card',
            name='dyspnea',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ecg_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ecg_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='focal_signs',
        ),
        migrations.RemoveField(
            model_name='card',
            name='formed_type_stool',
        ),
        migrations.RemoveField(
            model_name='card',
            name='general_assessment',
        ),
        migrations.RemoveField(
            model_name='card',
            name='glasgow_scale',
        ),
        migrations.RemoveField(
            model_name='card',
            name='heart_rate_deficit',
        ),
        migrations.RemoveField(
            model_name='card',
            name='heart_tone_accent',
        ),
        migrations.RemoveField(
            model_name='card',
            name='heartbite_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='heartbite_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='involved_in_the_act_of_breathing',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_brudzinski_symptom',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_kernig_symptom',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_murphy',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_obraztsova',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_ortner',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_pasternatsky',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_rovzinga',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_shchetkin_blumberg',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_sitkovsky',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_voskresensky',
        ),
        migrations.RemoveField(
            model_name='card',
            name='jaundice',
        ),
        migrations.RemoveField(
            model_name='card',
            name='kidney_punch',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='liver',
        ),
        migrations.RemoveField(
            model_name='card',
            name='lymph_nodes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='mkb',
        ),
        migrations.RemoveField(
            model_name='card',
            name='murmur',
        ),
        migrations.RemoveField(
            model_name='card',
            name='none_symptoms',
        ),
        migrations.RemoveField(
            model_name='card',
            name='normal_blood_pressure_diastolic',
        ),
        migrations.RemoveField(
            model_name='card',
            name='normal_blood_pressure_systolic',
        ),
        migrations.RemoveField(
            model_name='card',
            name='nuchal_rigidity',
        ),
        migrations.RemoveField(
            model_name='card',
            name='nystagmus',
        ),
        migrations.RemoveField(
            model_name='card',
            name='pain_stomach',
        ),
        migrations.RemoveField(
            model_name='card',
            name='painless_urination',
        ),
        migrations.RemoveField(
            model_name='card',
            name='paralysis',
        ),
        migrations.RemoveField(
            model_name='card',
            name='pulse_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='pulse_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='pupils_of_the_eyes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rash',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rate_stool',
        ),
        migrations.RemoveField(
            model_name='card',
            name='reaction_to_light',
        ),
        migrations.RemoveField(
            model_name='card',
            name='regular_stool',
        ),
        migrations.RemoveField(
            model_name='card',
            name='respiratory_rate_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='respiratory_rate_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='respiratory_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rhythmic_pulse',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rhythmic_tone',
        ),
        migrations.RemoveField(
            model_name='card',
            name='saturation_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='saturation_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='sensitive',
        ),
        migrations.RemoveField(
            model_name='card',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='card',
            name='start_time_of_hospitalization',
        ),
        migrations.RemoveField(
            model_name='card',
            name='status_localis',
        ),
        migrations.RemoveField(
            model_name='card',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='card',
            name='swelling',
        ),
        migrations.RemoveField(
            model_name='card',
            name='temperature_after',
        ),
        migrations.RemoveField(
            model_name='card',
            name='temperature_before',
        ),
        migrations.RemoveField(
            model_name='card',
            name='throat',
        ),
        migrations.RemoveField(
            model_name='card',
            name='time_of_arrival_at_hospital',
        ),
        migrations.RemoveField(
            model_name='card',
            name='time_of_receipt',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tone_of_heart',
        ),
        migrations.RemoveField(
            model_name='card',
            name='tonsils',
        ),
        migrations.RemoveField(
            model_name='card',
            name='transmission_time',
        ),
        migrations.RemoveField(
            model_name='card',
            name='wheezing',
        ),
        migrations.RemoveField(
            model_name='card',
            name='wheezing_localisation',
        ),
        migrations.RemoveField(
            model_name='card',
            name='zhaloby',
        ),
        migrations.RemoveField(
            model_name='card',
            name='сonsciousness',
        ),
        migrations.AlterField(
            model_name='card',
            name='cause',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AIDData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.TextField(null=True)),
                ('aid_effect', models.CharField(choices=[('improvement', 'Улучшение'), ('worsening', 'Ухудшение'), ('no_effects', 'Без эффекта')], default='improvement', max_length=100, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_data', to='card.card')),
            ],
            options={
                'db_table': 'AIDData',
            },
        ),
        migrations.CreateModel(
            name='AirData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratory_type', models.CharField(choices=[('vesicular', 'Везикулярное'), ('hard', 'Жёсткое'), ('bronchial', 'Бронхиальное'), ('puerile', 'Пуэриальное'), ('weakened', 'Ослабленное'), ('absent', 'Отсутствует')], default='vesicular', max_length=100, null=True)),
                ('wheezing', models.CharField(choices=[('none', 'Нет'), ('wet', 'Влажные'), ('dry', 'Сухие')], default='none', max_length=100, null=True)),
                ('wheezing_localisation', models.CharField(max_length=100, null=True)),
                ('dyspnea', models.CharField(choices=[('none', 'Нет'), ('inspiratory', 'Инспираторная'), ('expiratory', 'Экспираторная'), ('mixed', 'Смешанная')], default='none', max_length=100, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_data', to='card.card')),
            ],
            options={
                'db_table': 'AirData',
            },
        ),
        migrations.CreateModel(
            name='CommonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(null=True)),
                ('anamnesis', models.TextField(null=True)),
                ('general_assessment', models.CharField(choices=[('satisfactory', 'Удовлетворительное'), ('moderate', 'Средней степени тяжести'), ('severe', 'Тяжелое'), ('terminal', 'Терминальное')], default='satisfactory', max_length=100, null=True)),
                ('сonsciousness', models.CharField(choices=[('clear', 'Ясное'), ('confused', 'Оглушение'), ('stupor', 'Сопор'), ('coma', 'Кома')], default='clear', max_length=100, null=True)),
                ('glasgow_scale', models.IntegerField(null=True)),
                ('body_position', models.CharField(choices=[('active', 'Активное'), ('passive', 'Пассивное'), ('forced', 'Вынужденное')], default='active', max_length=100, null=True)),
                ('normal_blood_pressure_systolic', models.IntegerField(default=120, null=True)),
                ('normal_blood_pressure_diastolic', models.IntegerField(default=80, null=True)),
                ('status_localis', models.TextField(null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_data', to='card.card')),
            ],
            options={
                'db_table': 'CommonData',
            },
        ),
        migrations.CreateModel(
            name='DateTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_card', models.DateField(auto_now=True)),
                ('time_of_receipt', models.DateTimeField(null=True)),
                ('transmission_time', models.DateTimeField(null=True)),
                ('departure_time', models.DateTimeField(null=True)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('start_time_of_hospitalization', models.DateTimeField(null=True)),
                ('time_of_arrival_at_hospital', models.DateTimeField(null=True)),
                ('call_end_time', models.DateTimeField(null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_data', to='card.card')),
            ],
            options={
                'db_table': 'DateTimeData',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100, null=True)),
                ('mkb', models.CharField(max_length=100, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_data', to='card.card')),
            ],
            options={
                'db_table': 'DiagnosisData',
            },
        ),
        migrations.CreateModel(
            name='ECGData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_before', models.TextField(null=True)),
                ('ecg_after', models.TextField(null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_data', to='card.card')),
            ],
            options={
                'db_table': 'ECGData',
            },
        ),
        migrations.CreateModel(
            name='HeartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate_deficit', models.BooleanField(default=False, null=True)),
                ('heart_tone_accent', models.CharField(default='Нет', max_length=100, null=True)),
                ('rhythmic_tone', models.CharField(choices=[('rhythmic', 'Ритмичный'), ('arrhythmic', 'Аритмичный')], default='rhythmic', max_length=100, null=True)),
                ('tone_of_heart', models.CharField(choices=[('clear', 'Ясные'), ('muffled', 'Глухие'), ('dull', 'Приглушены'), ('absent', 'Отсутствуют')], default='clear', max_length=100, null=True)),
                ('murmur', models.CharField(choices=[('none', 'Нет'), ('systolic', 'Систолический'), ('diastolic', 'Диастолический'), ('pericardial_friction', 'Трения перикарда'), ('other', 'Другое')], default='none', max_length=100, null=True)),
                ('rhythmic_pulse', models.CharField(choices=[('rhythmic', 'Ритмичный'), ('arrhythmic', 'Аритмичный')], default='rhythmic', max_length=100, null=True)),
                ('characteristic_pulse', models.CharField(choices=[('normal', 'Нормальный'), ('weak_filling', 'Слабого наполнения'), ('tense', 'Напряжённый'), ('threadlike', 'Нитевидный'), ('absent', 'Отсутствует')], default='normal', max_length=100, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_data', to='card.card')),
            ],
            options={
                'db_table': 'HeartData',
            },
        ),
        migrations.CreateModel(
            name='NervousData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour', models.CharField(choices=[('calm', 'Спокойное'), ('excited', 'Возбуждённое'), ('aggressive', 'Агрессивное'), ('depressive', 'Депрессивное')], default='calm', max_length=100, null=True)),
                ('reaction_to_light', models.CharField(choices=[('yes', 'Есть'), ('no', 'Отсутствует')], default='yes', max_length=100, null=True)),
                ('pupils_of_the_eyes', models.CharField(choices=[('normal', 'Нормальные'), ('wide', 'Широкие'), ('narrow', 'Узкие')], default='normal', max_length=100, null=True)),
                ('anisocoria', models.BooleanField(default=False, null=True)),
                ('nystagmus', models.BooleanField(default=False, null=True)),
                ('focal_signs', models.BooleanField(default=False, null=True)),
                ('speech', models.CharField(choices=[('clear', 'Внятная'), ('aphasia', 'Афазия'), ('dysarthria', 'Дизартрия')], default='clear', max_length=100, null=True)),
                ('none_symptoms', models.BooleanField(default=True, null=True)),
                ('nuchal_rigidity', models.BooleanField(default=False, null=True)),
                ('is_kernig_symptom', models.BooleanField(default=False, null=True)),
                ('is_brudzinski_symptom', models.BooleanField(default=False, null=True)),
                ('paralysis', models.CharField(choices=[('none', 'Нет'), ('right', 'Справа'), ('left', 'Слева')], default='none', max_length=100, null=True)),
                ('sensitive', models.CharField(choices=[('preserved', 'Сохранена'), ('absent', 'Отсутствует'), ('reduced', 'Снижена'), ('left', 'Слева'), ('right', 'Справа')], default='preserved', max_length=100, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nervous_data', to='card.card')),
            ],
            options={
                'db_table': 'NervousData',
            },
        ),
        migrations.CreateModel(
            name='ParametersAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_after', models.FloatField(null=True)),
                ('respiratory_rate_after', models.IntegerField(null=True)),
                ('heartbite_after', models.IntegerField(null=True)),
                ('saturation_after', models.IntegerField(null=True)),
                ('pulse_after', models.IntegerField(null=True)),
                ('blood_pressure_systolic_after', models.IntegerField(null=True)),
                ('blood_pressure_diastolic_after', models.IntegerField(null=True)),
                ('blood_glucose_after', models.FloatField(null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_after_data', to='card.card')),
            ],
            options={
                'db_table': 'ParametersAfter',
            },
        ),
        migrations.CreateModel(
            name='ParametersBefore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_before', models.FloatField(null=True)),
                ('respiratory_rate_before', models.IntegerField(null=True)),
                ('heartbite_before', models.IntegerField(null=True)),
                ('saturation_before', models.IntegerField(null=True)),
                ('pulse_before', models.IntegerField(null=True)),
                ('blood_pressure_systolic_before', models.IntegerField(null=True)),
                ('blood_pressure_diastolic_before', models.IntegerField(null=True)),
                ('blood_glucose_before', models.FloatField(null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_before_data', to='card.card')),
            ],
            options={
                'db_table': 'ParametersBefore',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_cards', to='card.patient'),
        ),
        migrations.CreateModel(
            name='SkinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry_skin', models.CharField(choices=[('dry', 'Сухие'), ('moist', 'Влажные')], default='dry', max_length=100, null=True)),
                ('color_skin', models.CharField(choices=[('normal', 'Обычной окраски'), ('pale', 'Бледные'), ('hyperemic', 'Гиперемированные'), ('cyanotic', 'Цианоз')], default='normal', max_length=100, null=True)),
                ('jaundice', models.CharField(default='Нет', max_length=100, null=True)),
                ('rash', models.CharField(choices=[('none', 'Нет'), ('petechial', 'Петехиальная'), ('pustular', 'Пустулёзная'), ('vesicular', 'Везикулярная'), ('nodular', 'Узелковая'), ('other', 'Другое')], default='none', max_length=100, null=True)),
                ('throat', models.CharField(choices=[('calm', 'Спокоен'), ('hyperemic', 'Гиперемирован')], default='calm', max_length=100, null=True)),
                ('tonsils', models.CharField(default='Не увеличены', max_length=100, null=True)),
                ('lymph_nodes', models.CharField(default='Не увеличены', max_length=100, null=True)),
                ('swelling', models.CharField(choices=[('none', 'Нет'), ('legs', 'Голени'), ('face', 'Лицо'), ('torso', 'Туловище'), ('arms', 'Руки')], default='none', max_length=100, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_data', to='card.card')),
            ],
            options={
                'db_table': 'SkinData',
            },
        ),
        migrations.CreateModel(
            name='StomachData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liver', models.CharField(default='Не увеличена', max_length=100, null=True)),
                ('pain_stomach', models.CharField(max_length=100, null=True)),
                ('characteristic_stomach', models.CharField(choices=[('painless', 'Безболезненный'), ('painful', 'Болезненный')], default='painless', max_length=100, null=True)),
                ('involved_in_the_act_of_breathing', models.BooleanField(default=True, null=True)),
                ('formed_type_stool', models.CharField(choices=[('formed', 'Оформлен'), ('loose', 'Разжижен'), ('liquid', 'Жидкий'), ('absent', 'Отсутствует')], default='formed', max_length=100, null=True)),
                ('regular_stool', models.CharField(choices=[('regular', 'Регулярный'), ('irregular', 'Нерегулярный'), ('absent', 'Отсутствует')], default='regular', max_length=100, null=True)),
                ('rate_stool', models.IntegerField(default=1, null=True)),
                ('is_shchetkin_blumberg', models.BooleanField(default=False, null=True)),
                ('is_voskresensky', models.BooleanField(default=False, null=True)),
                ('is_ortner', models.BooleanField(default=False, null=True)),
                ('is_rovzinga', models.BooleanField(default=False, null=True)),
                ('is_pasternatsky', models.BooleanField(default=False, null=True)),
                ('is_sitkovsky', models.BooleanField(default=False, null=True)),
                ('is_obraztsova', models.BooleanField(default=False, null=True)),
                ('is_murphy', models.BooleanField(default=False, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stomach_data', to='card.card')),
            ],
            options={
                'db_table': 'StomachData',
            },
        ),
        migrations.CreateModel(
            name='UrinaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidney_punch', models.CharField(choices=[('negative_both', 'Отрицательный с обеих сторон'), ('positive_left', 'Положительный слева'), ('positive_right', 'Положительный справа'), ('positive_both', 'Положительный с обеих сторон'), ('weak_positive_left', 'Слабоположительный слева'), ('weak_positive_right', 'Слабоположительный справа'), ('weak_positive_both', 'Слабоположительный с обеих сторон')], default='negative_both', max_length=100, null=True)),
                ('characteristic_urine', models.CharField(choices=[('light_yellow', 'Светло-жёлтая'), ('cloudy', 'Мутная')], default='light_yellow', max_length=100, null=True)),
                ('with_inclusions', models.BooleanField(default=False, null=True)),
                ('with_sediment', models.BooleanField(default=False, null=True)),
                ('painless_urination', models.CharField(choices=[('painless', 'Безболезненное'), ('painful', 'Болезненное')], default='painless', max_length=100, null=True)),
                ('characteristic_urination', models.CharField(choices=[('free', 'Свободное'), ('difficult', 'Затруднено'), ('absent', 'Отсутствует')], default='free', max_length=100, null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urinary_data', to='card.card')),
            ],
            options={
                'db_table': 'UrinaryData',
            },
        ),
    ]
