# Generated by Django 5.2 on 2025-07-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_patient_remove_card_address_remove_card_aid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiddata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='airdata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='commondata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='datetimedata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='diagnosisdata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='ecgdata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='heartdata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='nervousdata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='parametersafter',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='skindata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='stomachdata',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='urinarydata',
            old_name='card_id',
            new_name='card',
        ),
    ]
