# Generated by Django 5.2 on 2025-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_rename_card_id_aiddata_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
