# Generated by Django 5.2 on 2025-07-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
