# Generated by Django 5.2 on 2025-07-22 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_remove_patient_address_card_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiddata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aid_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='airdata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='air_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='commondata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='datetimedata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datetime_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='diagnosisdata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='ecgdata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='heartdata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heart_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='nervousdata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nervous_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_after_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_before_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='skindata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skin_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='stomachdata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stomach_data', to='card.card'),
        ),
        migrations.AlterField(
            model_name='urinarydata',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='urinary_data', to='card.card'),
        ),
    ]
