# Generated by Django 5.2 on 2025-08-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_alter_aiddata_card_alter_airdata_card_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametersafter',
            old_name='blood_glucose_after',
            new_name='blood_glucose',
        ),
        migrations.RenameField(
            model_name='parametersafter',
            old_name='blood_pressure_diastolic_after',
            new_name='blood_pressure_diastolic',
        ),
        migrations.RenameField(
            model_name='parametersafter',
            old_name='blood_pressure_systolic_after',
            new_name='blood_pressure_systolic',
        ),
        migrations.RenameField(
            model_name='parametersafter',
            old_name='heartbite_after',
            new_name='heartbite',
        ),
        migrations.RenameField(
            model_name='parametersafter',
            old_name='pulse_after',
            new_name='pulse',
        ),
        migrations.RenameField(
            model_name='parametersafter',
            old_name='respiratory_rate_after',
            new_name='respiratory_rate',
        ),
        migrations.RenameField(
            model_name='parametersafter',
            old_name='saturation_after',
            new_name='saturation',
        ),
        migrations.RenameField(
            model_name='parametersafter',
            old_name='temperature_after',
            new_name='temperature',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='blood_glucose_before',
            new_name='blood_glucose',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='blood_pressure_diastolic_before',
            new_name='blood_pressure_diastolic',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='blood_pressure_systolic_before',
            new_name='blood_pressure_systolic',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='heartbite_before',
            new_name='heartbite',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='pulse_before',
            new_name='pulse',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='respiratory_rate_before',
            new_name='respiratory_rate',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='saturation_before',
            new_name='saturation',
        ),
        migrations.RenameField(
            model_name='parametersbefore',
            old_name='temperature_before',
            new_name='temperature',
        ),
        migrations.AlterField(
            model_name='commondata',
            name='сonsciousness',
            field=models.CharField(choices=[('clear', 'Ясное'), ('confused', 'Оглушение'), ('stupor', 'Сопор'), ('coma_1', 'Кома I'), ('coma_2', 'Кома II'), ('coma_3', 'Кома III')], default='clear', max_length=100, null=True),
        ),
    ]
