# Generated by Django 5.2 on 2025-08-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_rename_blood_glucose_after_parametersafter_blood_glucose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'MKB',
            },
        ),
        migrations.AlterField(
            model_name='nervousdata',
            name='paralysis',
            field=models.CharField(choices=[('none', 'Нет'), ('right', 'Справа'), ('left', 'Слева'), ('total', 'Обе стороны')], default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nervousdata',
            name='sensitive',
            field=models.CharField(choices=[('preserved', 'Сохранена'), ('absent', 'Отсутствует'), ('reduced', 'Снижена')], default='preserved', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skindata',
            name='swelling',
            field=models.CharField(choices=[('none', 'Нет'), ('legs', 'Голени'), ('face', 'Лицо'), ('torso', 'Туловище'), ('arms', 'Руки'), ('generalized', 'Генерализованные')], default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skindata',
            name='throat',
            field=models.CharField(choices=[('calm', 'Спокоен'), ('hyperemic', 'Гиперемирован'), ('pale', 'Бледный')], default='calm', max_length=100, null=True),
        ),
    ]
