# Generated by Django 5.2 on 2025-08-13 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_mkb_alter_nervousdata_paralysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisdata',
            name='mkb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mkb', to='card.mkb'),
        ),
    ]
