# Generated by Django 5.2 on 2025-08-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_alter_diagnosisdata_mkb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisdata',
            name='mkb',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
