# Generated by Django 5.2 on 2025-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_alter_diagnosisdata_mkb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdata',
            name='wheezing_localisation',
            field=models.CharField(default='Нет', max_length=100, null=True),
        ),
    ]
