# Generated by Django 5.2 on 2025-08-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_alter_airdata_wheezing_localisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondata',
            name='glasgow_scale',
            field=models.IntegerField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='blood_glucose',
            field=models.FloatField(default=5.5, null=True),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='blood_pressure_diastolic',
            field=models.IntegerField(default=80, null=True),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='blood_pressure_systolic',
            field=models.IntegerField(default=120, null=True),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='heartbite',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='pulse',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='respiratory_rate',
            field=models.IntegerField(default=16, null=True),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='saturation',
            field=models.IntegerField(default=98, null=True),
        ),
        migrations.AlterField(
            model_name='parametersafter',
            name='temperature',
            field=models.FloatField(default=36.6, null=True),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='blood_glucose',
            field=models.FloatField(default=5.5, null=True),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='blood_pressure_diastolic',
            field=models.IntegerField(default=80, null=True),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='blood_pressure_systolic',
            field=models.IntegerField(default=120, null=True),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='heartbite',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='pulse',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='respiratory_rate',
            field=models.IntegerField(default=16, null=True),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='saturation',
            field=models.IntegerField(default=98, null=True),
        ),
        migrations.AlterField(
            model_name='parametersbefore',
            name='temperature',
            field=models.FloatField(default=36.6, null=True),
        ),
        migrations.AlterField(
            model_name='stomachdata',
            name='pain_stomach',
            field=models.CharField(default='painless', max_length=100, null=True),
        ),
    ]
