# Generated by Django 5.2 on 2025-12-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_alter_commondata_glasgow_scale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commondata',
            old_name='сonsciousness',
            new_name='consciousness',
        ),
    ]
